.idea/.gitignore
.idea/checkstyle-idea.xml
.idea/compiler.xml
.idea/encodings.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/vcs.xml
ClubSocialAppCA/src/main/java/entities/Club.java
ClubSocialAppCA/src/main/java/entities/Post.java
ClubSocialAppCA/src/main/java/entities/Student.java
ClubSocialAppCA/src/main/java/entities/User.java
ClubSocialAppCA/src/main/java/use_case/club_create_post/sfdfsd.java
ClubSocialAppCA/src/main/java/use_case/club_get_member_list/nhjdsd.java
ClubSocialAppCA/src/main/java/use_case/club_remove_member/efrtwgw.java
ClubSocialAppCA/src/main/java/use_case/logout/sdfsd.java
ClubSocialAppCA/src/main/java/use_case/signup/club_signup/placeholder.java
ClubSocialAppCA/src/main/java/use_case/signup/user_signup/place1.java
ClubSocialAppCA/src/main/java/use_case/student_interact_post/like_post/cfdfdsf.java
ClubSocialAppCA/src/main/java/use_case/student_interact_post/register_event/gregegw.java
ClubSocialAppCA/src/main/java/use_case/user_join_club/dsd.java
ClubSocialAppCA/src/main/java/use_case/user_leave_club/ewew.java
ClubSocialAppCA/src/main/java/use_case/user_search_club/wew.java

Added initial use_case template

initial use_case setup

---

gitignore

Added .gitignore

---

src/main/java/use_case/user_join_club/UserJoinClubAccessInterface.java
src/main/java/use_case/user_join_club/UserJoinClubInputBoundary.java
src/main/java/use_case/user_join_club/UserJoinClubInputData.java
src/main/java/use_case/user_join_club/UserJoinClubInteractor.java
src/main/java/use_case/user_join_club/UserJoinClubOutputBoundary.java
src/main/java/use_case/user_join_club/UserJoinClubOutputData.java
src/main/java/use_case/user_join_club/dsd.java
src/main/java/use_case/user_leave_club/UserLeaveClubAccessInterface.java
src/main/java/use_case/user_leave_club/UserLeaveClubInputBoundary.java
src/main/java/use_case/user_leave_club/UserLeaveClubInputData.java
src/main/java/use_case/user_leave_club/UserLeaveClubInteractor.java
src/main/java/use_case/user_leave_club/UserLeaveClubOutputBoundary.java
src/main/java/use_case/user_leave_club/UserLeaveClubOutputData.java
src/main/java/use_case/user_leave_club/ewew.java
src/main/java/use_case/user_search_club/UserSearchClubAccessInterface.java
src/main/java/use_case/user_search_club/UserSearchClubInputBoundary.java
src/main/java/use_case/user_search_club/UserSearchClubInputData.java
src/main/java/use_case/user_search_club/UserSearchClubInteractor.java
src/main/java/use_case/user_search_club/UserSearchClubOutputBoundary.java
src/main/java/use_case/user_search_club/UserSearchClubOutputData.java
src/main/java/use_case/user_search_club/wew.java

Userjoinclub UserLeaveClub UserSearchclub added files format

Userjoinclub UserLeaveClub UserSearchclub added files format

---

mystyle.xml
src/main/java/entities/Announcement.java
src/main/java/entities/Club.java
src/main/java/entities/Post.java
src/main/java/entities/Student.java
src/main/java/entities/User.java

I wrote the code for the different entities. Please read through the code and let me know what you think before merging.
For the Post entity, I only implemented announcements for now. If we have time later, I can add more. 
(I tried adding comments and descriptions to make the code more clear)
Finally, I pushed a style file. Please download and set up CheckStyle.

Entity creation

---

src/main/java/interface_adapter/data_access/DataAccessController.java
src/main/java/interface_adapter/data_access/DataAccessPresenter.java
src/main/java/interface_adapter/data_access/HomeState.java
src/main/java/interface_adapter/data_access/HomeViewModel.java
src/main/java/interface_adapter/login/LoginController.java
src/main/java/interface_adapter/login/LoginPresenter.java
src/main/java/interface_adapter/login/LoginState.java
src/main/java/interface_adapter/login/LoginViewModel.java

Only thing missing is prepare success view in LoginPresenter. Waiting for temp view to be updated with state.

Finished most of login for interface adapter.

---

src/main/java/interface_adapter/login/LoginState.java
src/main/java/interface_adapter/login/LoginViewModel.java

removed instance variables in LoginViewModel and changed LoginState to have one error

Pretty up login stuff in interface_adapter

---

src/main/java/use_case/login/LoginInputBoundary.java
src/main/java/use_case/login/LoginInputData.java
src/main/java/use_case/login/LoginOutputBoundary.java

Completion of input and output. Will have to implement DAI and interactor.

Use case login

---

README.md
src/main/java/interface_adapter/signup/club_signup/ClubSignupPresenter.java
src/main/java/interface_adapter/signup/student_signup/StudentSignupController.java
src/main/java/interface_adapter/signup/student_signup/StudentSignupPresenter.java
src/main/java/use_case/signup/club_signup/ClubSignupInputBoundary.java
src/main/java/use_case/signup/club_signup/ClubSignupInputData.java
src/main/java/use_case/signup/club_signup/ClubSignupInteractor.java
src/main/java/use_case/signup/club_signup/ClubSignupOutputBoundary.java
src/main/java/use_case/signup/club_signup/ClubSignupOutputData.java
src/main/java/use_case/signup/club_signup/ClubSignupUserDataAccessInterface.java
src/main/java/use_case/signup/student_signup/StudentSignupInputBoundary.java
src/main/java/use_case/signup/student_signup/StudentSignupInputData.java
src/main/java/use_case/signup/student_signup/StudentSignupInteractor.java
src/main/java/use_case/signup/student_signup/StudentSignupOutputBoundary.java
src/main/java/use_case/signup/student_signup/StudentSignupOutputData.java
src/main/java/use_case/signup/student_signup/StudentSignupUserDataAccessInterface.java

split the signup use case into two; one is for club signups and another is for student signups

split signup usecase into two

---

src/main/java/view/LoginView.java

Renamed the view name instance variable in LoginView to be the same as its view model

Fixed not being able to switch to login view from signup

---

README.md
src/main/java/app/AppBuilder.java
src/main/java/data_access/UserDataAccessObject.java
src/main/java/entity/user/Club.java
src/main/java/interface_adapter/club_logged_in/ClubLoggedInState.java
src/main/java/interface_adapter/club_logged_in/create_post/CreatePostState.java
src/main/java/use_case/club_create_post/ClubCreatePostInteractor.java
src/main/java/use_case/club_get_members/ClubGetMembersOutputBoundary.java
src/main/java/use_case/club_remove_member/ClubRemoveMemberInputBoundary.java
src/main/java/use_case/club_remove_member/ClubRemoveMemberInputData.java
src/main/java/use_case/club_remove_member/ClubRemoveMemberInteractor.java
src/main/java/use_case/club_remove_member/ClubRemoveMemberOutputBoundary.java
src/main/java/use_case/club_remove_member/ClubRemoveMemberOutputData.java
src/main/java/use_case/club_remove_member/ClubRemoveMemberUserDataAccessInterface.java
src/main/java/view/CreatePostView.java
src/main/java/view/LabelTextPanel.java

1) Bug fixes and typo corrections (java docs)
2) Completed the club remove member use case
3) Revamped the clubbed_logged_in interface adapter so that all state classes inherit from one general ClubLoggedInState class with all the necessary extra information.
4) Added a LabelTextPanel Class for easier programming and less redundant code.
5) Added the necessary methods in the DAO related to the create post use case
6) Finally updated the readme to showcase my work from this week

Addition of a lot of stuff. See description.

---

pom.xml
src/main/java/data_access/FirestoreUserDataAccessObject.java

Working on implementing persisting data access model using Firestore.

Firestore db

---

src/main/java/data_access/FirestoreUserDataAccessObject.java
src/main/java/data_access/UserDataAccessObject.java
src/main/java/entity/user/ClubUserFactory.java
src/main/java/entity/user/StudentUserFactory.java
src/main/java/use_case/signup/club_signup/ClubSignupInteractor.java
src/main/java/use_case/signup/club_signup/ClubSignupUserDataAccessInterface.java
src/main/java/use_case/signup/student_signup/StudentSignupInteractor.java
src/main/java/use_case/signup/student_signup/StudentSignupUserDataAccessInterface.java

Before, users would not get assigned individual identification when they were created. Now, they each get a unique id when the user gets created, through sign up.
Note, that I added methods that must be implemented in the DAO.

Added user id creation when new user is created

---

src/main/java/data_access/UserDataAccessObject.java
src/main/java/entity/data_structure/DataStore.java
src/main/java/entity/data_structure/DataStoreArrays.java
src/main/java/entity/post/Announcement.java
src/main/java/entity/user/Club.java
src/main/java/entity/user/ClubFactory.java
src/main/java/entity/user/ClubUserFactory.java
src/main/java/entity/user/Student.java
src/main/java/entity/user/StudentFactory.java
src/main/java/entity/user/StudentUserFactory.java
src/main/java/use_case/club_get_members/ClubGetMembersInteractor.java
src/main/java/use_case/club_get_members/ClubGetMembersOutputData.java
src/main/java/use_case/login/club_login/ClubLoginOutputData.java
src/main/java/use_case/login/student_login/StudentLoginOutputData.java

What?
Migrated the old code base that used ArrayLists as the primary data structure to store the values of students, clubs, and posts. However, this implementation was not compliant with the open closed principle, since changing the data structure involved making several changes across our entire code base. By changing over the instances of ArrayList over to an abstract data structure called DataStore, the core functionality of the data structure persists but the inner implementation is free to change with minimal changes, making the code compliant with SOLID principles. 
Why?
Recently we changed over our code from using HashMaps into using ArrayLists, which was a long process and prone to error. This issue highlighted a design flaw and lead us to develop a more permanent solution, by …

Data structure wrapper 

---

src/main/java/interface_adapter/club_logged_in/ClubLoggedInState.java
src/main/java/interface_adapter/club_logged_in/get_members/GetMembersPresenter.java
src/main/java/interface_adapter/club_logged_in/remove_member/RemoveMemberPresenter.java
src/main/java/use_case/club_get_members/ClubGetMembersInteractor.java
src/main/java/use_case/club_get_members/ClubGetMembersOutputData.java
src/main/java/view/ClubPageView.form
src/main/java/view/ClubPageView.java

I refactored the code to have no entities in the interface adapter layer. That meant changing the output data, interactor and presenter code.
Note, that I only did my part, and that other group members need to do the same.
Check the commits to see changed files.

Individual club page

---

src/main/java/data_access/ClubFirestoreUserDataAccessObject.java
src/main/java/data_access/StudentFirestoreUserDataAccessObject.java
src/main/java/use_case/explore_clubs/ExploreClubsInteractor.java
src/main/java/use_case/student_profile/StudentProfileAccessInterface.java
src/main/java/view/ExploreClubsView.form
src/main/java/view/ExploreClubsView.java

In this PR I added the necessary files that were left from the use cases into the firebase DAO so that they are ready to use. No extra implementation was necessary, just needed extra imports.

Firestore implementation of remaining use cases

---

src/main/java/view/ExploreClubsView.java

Fixed ExploreClubsView from referencing the wrong name for its controller class.

ExploreClubsView Fix

---

src/main/java/data_access/InMemoryUserDataAccessObject.java
src/test/java/use_case/student_leave_club/StudentLeaveClubInteractorTest.java

Completed the Join and Leave use cases pull requests. All tests hit 100% code coverage and pass on my end. Let me know if you spot any issues!

kabir-testcases

---

src/main/java/use_case/signup/club_signup/ClubSignupInteractor.java
src/main/java/use_case/signup/club_signup/ClubSignupOutputData.java
src/main/java/use_case/signup/student_signup/StudentSignupInteractor.java
src/main/java/use_case/signup/student_signup/StudentSignupOutputData.java
src/test/java/use_case/club_get_posts/ClubGetPostsInteractorTest.java
src/test/java/use_case/club_update_desc/ClubUpdateDescInteractorTest.java
src/test/java/use_case/signup/club_signup/ClubSignupInteractorTest.java
src/test/java/use_case/signup/student_signup/StudentSignupInteractorTest.java

I edited all of my Tests to have 100% coverage in their respective use cases.
Both ClubSignup and StudentSignup Interactors were fixed to pass their tests.

Roy Test Fixes and Coverage

---

LICENSE
README.md

Included an MIT Licence to the GitHub. Also added a template for our README.md from the CSC207 Course Page.
Currently, the licence holder is Karl, since he made the repository.

Roy LISCENCE and README

---

src/main/java/app/AppBuilder.java
src/main/java/app/Main.java
src/main/java/view/ClubCreatePostView.java

Fixed ClubCreatePostView to not require a controller in its constructor. Also refactored it to be more consistent name wise. 
Made it so AppBuilder can run in main.
Note that while the app does run, we cannot get past the signup because of a bug in the signup. This bug is fixed in #76.

AppBuilder Working and ClubCreatePost Refactoring

---

src/main/java/entity/post/Announcement.java
src/main/java/entity/post/Post.java
src/test/java/entity/data_structure/DataStoreArraysTest.java
src/test/java/entity/post/PostEntityTest.java

Fixed some minor bugs and wrote tests for the Datastore and Announcement entity. Overall the performance was good from my tests, no major issues, although one change was spotted in the Announcement class where it was returning null for getting dislikes. Thank fully the test picked it up!

Kabir testcases

---

src/main/java/app/Main.java
src/main/java/view/ClubLoggedInView.java

Fixed Infinite Recursion in the ClubLoggedInView when its propertyChanged method was called.
Also added a missing use case into Main

Fixed Infinite Recursion in ClubLoggedInView

---

src/test/java/use_case/club_get_posts/ClubGetPostsInteractorTest.java

Made ClubGetPostsInteractorTest more comprehensive by using 2 posts rather than 1 in the test.

Removed casting in ClubGetPostsInteractorTest and increased post count

---

src/main/java/app/AppBuilder.java
src/main/java/view/StudentHomeView.java

Fixed the infinite recursion bug in StudentHomeView and made it so logout worked in the view

Roy bugfixes

---

src/main/java/interface_adapter/club_logged_in/club_create_post/ClubCreatePostPresenter.java
src/main/java/use_case/club_create_post/ClubCreatePostInteractor.java
src/main/java/view/ClubCreatePostView.java
src/main/java/view/ClubLoggedInView.form
src/main/java/view/ClubLoggedInView.java
src/main/java/view/PostTextPanel.form
src/main/java/view/PostTextPanel.java
src/main/java/view/RemoveMemberPanel.java

Fixed the issue of Posts not  showing up after creation. Also decorated the ClubLoggedInView to be more user friendly.

Roy createandshowpostfix

---

src/main/java/interface_adapter/club_logged_in/club_create_post/ClubCreatePostPresenter.java
src/main/java/interface_adapter/club_logged_in/club_create_post/ClubCreatePostState.java
src/main/java/view/ClubCreatePostView.java

As the title suggest, I fixed all issues related to create club post. 
Before, when creating a post, the view would not make a popup for errors. To be more specific, the change property method was never accessed. It got fixed.
Also added comments and made some style changed. Everything works fine now.

Fixed all the issues related to club create post

---

src/main/java/app/AppBuilder.java
src/main/java/app/Main.java
src/main/java/data_access/InMemoryUserDataAccessObject.java
src/main/java/interface_adapter/club_get_posts/ClubGetPostsPresenter.java
src/main/java/interface_adapter/club_logged_in/club_get_members/ClubGetMembersPresenter.java
src/main/java/interface_adapter/club_logged_in/club_remove_member/ClubRemoveMemberPresenter.java
src/main/java/interface_adapter/club_update_desc/ClubUpdateDescPresenter.java
src/main/java/view/ClubLoggedInView.java

Added ClubRemoveMember use case to main and AppBuilder.java. Fixed members not displaying in ClubLoggedInView. Changed ClubLoggedInView messages to be popups.
I also added a constructor in the in memory DAO for testing purposes. This will be removed later.

Get Members and Remove Member fix in ClubLoggedInView

---

src/main/java/data_access/ClubFirestoreUserDataAccessObject.java
src/main/java/data_access/InMemoryUserDataAccessObject.java
src/main/java/data_access/StudentFirestoreUserDataAccessObject.java
src/main/java/interface_adapter/club_get_posts/ClubGetPostsPresenter.java
src/main/java/interface_adapter/club_update_desc/ClubUpdateDescPresenter.java
src/main/java/interface_adapter/logout/LogoutPresenter.java
src/main/java/interface_adapter/signup/club_signup/ClubSignupPresenter.java
src/main/java/interface_adapter/signup/student_signup/StudentSignupPresenter.java
src/main/java/use_case/club_get_posts/ClubGetPostsInteractor.java
src/main/java/use_case/signup/club_signup/ClubSignupDataAccessInterface.java
src/main/java/use_case/signup/club_signup/ClubSignupInteractor.java
src/main/java/use_case/signup/student_signup/StudentSignupDataAccessInterface.java
src/main/java/use_case/signup/student_signup/StudentSignupInteractor.java
src/main/java/view/ClubLoggedInView.java
src/test/java/use_case/signup/club_signup/ClubSignupInteractorTest.java
src/test/java/use_case/signup/student_signup/StudentSignupInteractorTest.java

Added more comments inside of the classes I have worked on for more technical documentation. Also fixed a minor bug in ClubGetPostsPresenter, which called the wrong property changed argument for displaying a message in ClubLoggedInView.
Also renamed the signup data access interfaces to not have "User" in them for consistency with other use cases.

Roy Added More Comments and a minor bug fix

---

src/main/java/view/ClubLoggedInView.java
src/main/java/view/PostTextPanel.form
src/main/java/view/RemoveMemberPanel.form

Updated ClubLoggedInView to display the latest post. Also added borders to each member and post.

ClubLoggedInView modifications

---

src/main/java/interface_adapter/student_logged_in/explore_clubs/ExploreClubsPresenter.java
src/main/java/use_case/student_homepage/show_clubs/StudentShowClubsInteractor.java
src/main/java/view/ClubDescriptionExploreContainer.java
src/main/java/view/ClubMiniPanel.java
src/main/java/view/ClubPageView.java
src/main/java/view/ClubsContainer.java
src/main/java/view/StudentHomeView.java

Fixed the club info page when entered from the student home view

Club info button fix

---

accessibility-report.md
src/main/java/use_case/signup/club_signup/ClubSignupInteractor.java
src/main/java/use_case/signup/student_signup/StudentSignupInteractor.java
src/test/java/use_case/signup/club_signup/ClubSignupInteractorTest.java
src/test/java/use_case/signup/student_signup/StudentSignupInteractorTest.java

Added and completed most of the accessibility report other than question 3. 
Fixed error when trying to signup with empty input fields. This was caused by the Firebase DAO not allowing for empty strings to be used to search for things in the database.
I also edited the tests for signup interactors to have 100% coverage.

Accessibility report and signup interactor fix

---

src/main/java/view/ClubLoggedInView.form
src/main/java/view/ClubLoggedInView.java
src/main/java/view/PostTextPanel.form
src/main/java/view/PostTextPanel.java
src/main/java/view/RemoveMemberPanel.form
src/main/java/view/RemoveMemberPanel.java

Before, the club posts and Club names were not displayed properly due to the properties of JLabel. I have replaced some of them with JTextPane instead of JLabel, and added them into a JSrollPane so all the text can be seen.

Edit Panels in ClubLoggedInView

---

src/main/java/app/Main.java
src/main/java/view/ClubMiniPanel.form
src/main/java/view/PageView.form
src/main/java/view/PostPanel.form
src/main/java/view/PostPanel.java
src/main/java/view/PostsContainer.java

fixed all the dimensions in the student home view to look proper.

made student home view look nice.

---

accessibility-report.md

Finished the accessibility report.

Updated accessibility-report.md to have the 3rd question be complete

---

src/main/java/app/Main.java
src/main/java/data_access/StudentFirestoreUserDataAccessObject.java
src/main/java/entity/data_structure/DataStoreArrays.java
src/main/java/entity/user/Club.java
src/main/java/use_case/explore_clubs/ExploreClubsInteractor.java
src/main/java/use_case/student_profile/StudentProfileAccessInterface.java
src/main/java/use_case/student_profile/StudentProfileInputData.java
src/main/java/use_case/student_profile/StudentProfileOutputData.java
src/main/java/use_case/student_search_club/StudentSearchClubAccessInterface.java
src/main/java/use_case/student_search_club/StudentSearchClubInputBoundary.java
src/main/java/use_case/student_search_club/StudentSearchClubInputData.java
src/main/java/use_case/student_search_club/StudentSearchClubInteractor.java
src/main/java/use_case/student_search_club/StudentSearchClubOutputBoundary.java
src/main/java/use_case/student_search_club/StudentSearchClubOutputData.java
src/main/java/view/ExploreClubsView.java
src/test/java/entity/data_structure/DataStoreArraysTest.java
src/test/java/entity/post/PostEntityTest.java
src/test/java/entity/user/ClubTests.java
src/test/java/entity/user/StudentTest.java
src/test/java/use_case/explore_clubs/ExploreClubsInteractorTest.java
src/test/java/use_case/student_homepage/StudentHomeInteractorTest.java
src/test/java/use_case/student_homepage/dislike/StudentDislikeInteractorTest.java
src/test/java/use_case/student_homepage/like/StudentLikeInteractorTest.java
src/test/java/use_case/student_homepage/show_clubs/StudentShowClubsInteractorTest.java
src/test/java/use_case/student_profile/StudentProfileInteractorTest.java

Finishing the last bit of code coverage tests

Finishing test coverage

---

src/main/java/app/Main.java
src/main/java/view/ClubMiniPanel.java
src/main/java/view/ClubPageView.form
src/main/java/view/ClubPageView.java

changed a few final visual parameters

---

src/main/java/app/Main.java
src/main/java/entity/user/ClubUserFactory.java
src/main/java/entity/user/StudentUserFactory.java

Slight solid fix
